/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./web/templates/**/*.html",
    "./web/static/**/*.js"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#535f70",
        "inverse-on-surface": "#ecf0fe",
        "inverse-primary": "#a8c8ff",
        "on-surface-dark": "#e2e2e5",
        "on-secondary-fixed": "#101c2b",
        "accent-media": "#8b5cf6",
        "primary-fixed-dim": "#a8c8ff",
        "on-surface-variant": "#424751",
        "primary-container": "#00488d",
        "surface-container-lowest": "#ffffff",
        "surface": "#f9f9ff",
        "surface-tint": "#295ea4",
        "outline-variant-light": "#c2c6d4",
        "on-tertiary-fixed-variant": "#00468b",
        "inverse-surface": "#2b313b",
        "accent-danger-pdf": "#ba1a1a",
        "accent-go": "#00add8",
        "surface-container-light": "#eeeef0",
        "surface-container-highest-dark": "#2e3238",
        "surface-dim": "#d5dae7",
        "on-surface-variant-light": "#424752",
        "tertiary-container": "#00488e",
        "on-surface-light": "#1a1c1e",
        "on-surface-variant-dark": "#c2c6d4",
        "on-surface": "#161c25",
        "surface-bright": "#f9f9ff",
        "outline-variant": "#c2c6d2",
        "accent-sheet": "#10b981",
        "outline-variant-dark": "#383c44",
        "on-primary-fixed-variant": "#00468a",
        "accent-js": "#f59e0b",
        "surface-variant": "#dee2f0",
        "tertiary-fixed-dim": "#a8c8ff",
        "on-tertiary-container": "#8fb9ff",
        "secondary-fixed-dim": "#bbc7db",
        "primary": "#003265",
        "error-container": "#ffdad6",
        "surface-container-high-light": "#e8e8ea",
        "surface-light": "#f9f9fc",
        "on-secondary-container": "#596576",
        "on-primary": "#ffffff",
        "background": "#f9f9ff",
        "on-error": "#ffffff",
        "on-primary-container": "#8eb9ff",
        "on-primary-fixed": "#001b3c",
        "primary-fixed": "#d6e3ff",
        "secondary-container": "#d7e3f8",
        "on-tertiary-fixed": "#001b3d",
        "surface-container-dark": "#1e2024",
        "surface-container-high-dark": "#24272c",
        "primary-dark": "#a8c8ff",
        "surface-container-high": "#e4e8f6",
        "on-secondary": "#ffffff",
        "surface-container-highest-light": "#e2e2e5",
        "surface-dark": "#121316",
        "surface-container-low-light": "#f3f3f6",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d7e3f8",
        "on-background": "#161c25",
        "surface-container-low-dark": "#181a1d",
        "primary-container-dark": "#00468b",
        "outline": "#737782",
        "on-secondary-fixed-variant": "#3c4858",
        "tertiary": "#003266",
        "on-tertiary": "#ffffff",
        "surface-container": "#e9eefb",
        "error": "#ba1a1a",
        "tertiary-fixed": "#d6e3ff",
        "surface-container-highest": "#dee2f0",
        "surface-container-low": "#f0f3ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "2rem",
        "space-md": "1rem",
        "gutter": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "margin": "1rem",
        "gutter-desktop": "1.5rem"
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "sans-serif"],
        "mono": ["JetBrains Mono", "ui-monospace", "monospace"],
        "mono-tabular": ["JetBrains Mono", "ui-monospace", "monospace"],
        "title-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "mono-tabular": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms')({ strategy: 'class' }),
    require('@tailwindcss/container-queries')
  ]
};
